Add many missing deps
This resolves for me the for me the following compilation errors on hydra:

```
src/enzyme_ad/jax/RegistryUtils.cpp:1:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h'
    1 | #include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMToLLVMIRTranslation.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:2:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Target/LLVMIR/Dialect/NVVM/NVVMToLLVMIRTranslation.h'
    2 | #include "mlir/Target/LLVMIR/Dialect/NVVM/NVVMToLLVMIRTranslation.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:7:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/Func/Extensions/InlinerExtension.h'
    7 | #include "mlir/Dialect/Func/Extensions/InlinerExtension.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:8:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/LLVMIR/Transforms/InlinerInterfaceImpl.h'
    8 | #include "mlir/Dialect/LLVMIR/Transforms/InlinerInterfaceImpl.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:9:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/Tensor/IR/Tensor.h'
    9 | #include "mlir/Dialect/Tensor/IR/Tensor.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:11:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'Dialect/Dialect.h'
   11 | #include "Dialect/Dialect.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:13:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/ArithToLLVM/ArithToLLVM.h'
   13 | #include "mlir/Conversion/ArithToLLVM/ArithToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:14:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/ComplexToLLVM/ComplexToLLVM.h'
   14 | #include "mlir/Conversion/ComplexToLLVM/ComplexToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:15:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h'
   15 | #include "mlir/Conversion/ControlFlowToLLVM/ControlFlowToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:16:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/ConvertToLLVM/ToLLVMPass.h'
   16 | #include "mlir/Conversion/ConvertToLLVM/ToLLVMPass.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:17:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h'
   17 | #include "mlir/Conversion/FuncToLLVM/ConvertFuncToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:18:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/IndexToLLVM/IndexToLLVM.h'
   18 | #include "mlir/Conversion/IndexToLLVM/IndexToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:19:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/MathToLLVM/MathToLLVM.h'
   19 | #include "mlir/Conversion/MathToLLVM/MathToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:20:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/MemRefToLLVM/MemRefToLLVM.h'
   20 | #include "mlir/Conversion/MemRefToLLVM/MemRefToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:21:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/NVVMToLLVM/NVVMToLLVM.h'
   21 | #include "mlir/Conversion/NVVMToLLVM/NVVMToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:22:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/OpenMPToLLVM/ConvertOpenMPToLLVM.h'
   22 | #include "mlir/Conversion/OpenMPToLLVM/ConvertOpenMPToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:23:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/UBToLLVM/UBToLLVM.h'
   23 | #include "mlir/Conversion/UBToLLVM/UBToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:24:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h'
   24 | #include "mlir/Conversion/VectorToLLVM/ConvertVectorToLLVM.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:25:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/Affine/IR/AffineOps.h'
   25 | #include "mlir/Dialect/Affine/IR/AffineOps.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:26:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/Async/IR/Async.h'
   26 | #include "mlir/Dialect/Async/IR/Async.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:27:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/Complex/IR/Complex.h'
   27 | #include "mlir/Dialect/Complex/IR/Complex.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:28:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/ControlFlow/IR/ControlFlow.h'
   28 | #include "mlir/Dialect/ControlFlow/IR/ControlFlow.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:29:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/DLTI/DLTI.h'
   29 | #include "mlir/Dialect/DLTI/DLTI.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:30:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/Func/IR/FuncOps.h'
   30 | #include "mlir/Dialect/Func/IR/FuncOps.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:31:10: error: module //src/enzyme_ad/jax:compile_with_xla does not depend on a module exporting 'mlir/Dialect/GPU/IR/GPUDialect.h'
   31 | #include "mlir/Dialect/GPU/IR/GPUDialect.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:32:10: error: module //src/enzyme_ad/jax:compile_with_xla does not depend on a module exporting 'mlir/Dialect/LLVMIR/NVVMDialect.h'
   32 | #include "mlir/Dialect/LLVMIR/NVVMDialect.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:33:10: error: module //src/enzyme_ad/jax:compile_with_xla does not depend on a module exporting 'mlir/Dialect/Linalg/IR/Linalg.h'
   33 | #include "mlir/Dialect/Linalg/IR/Linalg.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:35:10: error: module //src/enzyme_ad/jax:compile_with_xla does not depend on a module exporting 'mlir/Dialect/Math/IR/Math.h'
   35 | #include "mlir/Dialect/Math/IR/Math.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:36:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/MemRef/IR/MemRef.h'
   36 | #include "mlir/Dialect/MemRef/IR/MemRef.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:37:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/NVGPU/IR/NVGPUDialect.h'
   37 | #include "mlir/Dialect/NVGPU/IR/NVGPUDialect.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:38:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/OpenMP/OpenMPDialect.h'
   38 | #include "mlir/Dialect/OpenMP/OpenMPDialect.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:39:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/SCF/IR/SCF.h'
   39 | #include "mlir/Dialect/SCF/IR/SCF.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:40:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/Transform/IR/TransformDialect.h'
   40 | #include "mlir/Dialect/Transform/IR/TransformDialect.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:41:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/UB/IR/UBOps.h'
   41 | #include "mlir/Dialect/UB/IR/UBOps.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:42:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Dialect/Vector/IR/VectorOps.h'
   42 | #include "mlir/Dialect/Vector/IR/VectorOps.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:44:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Target/LLVMIR/Dialect/Builtin/BuiltinToLLVMIRTranslation.h'
   44 | #include "mlir/Target/LLVMIR/Dialect/Builtin/BuiltinToLLVMIRTranslation.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:45:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Target/LLVMIR/Dialect/GPU/GPUToLLVMIRTranslation.h'
   45 | #include "mlir/Target/LLVMIR/Dialect/GPU/GPUToLLVMIRTranslation.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:46:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.h'
   46 | #include "mlir/Target/LLVMIR/Dialect/OpenMP/OpenMPToLLVMIRTranslation.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:47:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'stablehlo/dialect/ChloOps.h'
   47 | #include "stablehlo/dialect/ChloOps.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:48:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'stablehlo/dialect/StablehloOps.h'
   48 | #include "stablehlo/dialect/StablehloOps.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:49:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'xla/mlir_hlo/mhlo/IR/hlo_ops.h'
   49 | #include "xla/mlir_hlo/mhlo/IR/hlo_ops.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:51:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMIRToLLVMTranslation.h'
   51 | #include "mlir/Target/LLVMIR/Dialect/LLVMIR/LLVMIRToLLVMTranslation.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:52:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'mlir/Target/LLVMIR/Dialect/NVVM/LLVMIRToNVVMTranslation.h'
   52 | #include "mlir/Target/LLVMIR/Dialect/NVVM/LLVMIRToNVVMTranslation.h"
      |          ^
src/enzyme_ad/jax/RegistryUtils.cpp:54:10: error: module //src/enzyme_ad/jax:enzyme_call.so does not depend on a module exporting 'shardy/dialect/sdy/ir/dialect.h'
   54 | #include "shardy/dialect/sdy/ir/dialect.h"
      |          ^
```

Similar errors for the `compile_with_xla` target.