[CI] Don't write last commit message on the JAX branch to a file (#1424)
This seems to cause some troubles:
```
Error: Unable to process file command 'env' successfully.
Error: Invalid format 'Diff: https://github.com/jax-ml/jax/compare/4455434869812dfb7336b18f2e59a8690ba38e79...6c1760b695ee770c18f9a8b2f767398294a2c983'
```
Let's simply use regular variables without further complications.