Add missing dependency to `src/enzyme_ad/jax:XLADerivatives` (#374)
This seems to solve for me locally the error
```
[05:01:02] external/enzyme_ad/src/enzyme_ad/jax/Passes/AffineToStableHLORaising.cpp:19:10: error: module @enzyme_ad//src/enzyme_ad/jax:XLADerivatives does not depend on a module exporting 'mlir/Dialect/Affine/LoopUtils.h'
[05:01:02]    19 | #include "mlir/Dialect/Affine/LoopUtils.h"
[05:01:02]       |          ^
[05:01:02] 1 error generated.
```